//Victor Fares Correa Auad Pereira RA2525542
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormCadVis extends javax.swing.JFrame {
    private Visitante vis1;
    private GerVis gv = GerVis.geraGerVis();
    private static FormCadVis cpUnic;
    
    private FormCadVis() {
        initComponents();
    }
    
    //Singleton
    public static FormCadVis geraCadVis() {
        if(cpUnic == null) {
            cpUnic = new FormCadVis();
        }
        return cpUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotNome = new javax.swing.JLabel();
        rotCpf = new javax.swing.JLabel();
        rotIdade = new javax.swing.JLabel();
        rotSexo = new javax.swing.JLabel();
        rotRg = new javax.swing.JLabel();
        rotPacVis = new javax.swing.JLabel();
        cxVisNome = new javax.swing.JTextField();
        cxVisCpf = new javax.swing.JTextField();
        cxVisIdade = new javax.swing.JTextField();
        cxVisSexo = new javax.swing.JTextField();
        cxVisRg = new javax.swing.JTextField();
        cxVisPac = new javax.swing.JTextField();
        btInserir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVis = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE VISITANTES");

        rotNome.setText("Nome");

        rotCpf.setText("CPF");

        rotIdade.setText("Idade");

        rotSexo.setText("Sexo");

        rotRg.setText("RG");

        rotPacVis.setText("Paciente Visitado");

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btDeletar.setText("Deletar");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btConsulta.setText("Consulta por RG");
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        tbVis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "RG", "Idade", "Paciente Visitado", "Sexo"
            }
        ));
        tbVis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxVisNome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxVisCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxVisIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxVisSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotRg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxVisRg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotPacVis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxVisPac, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btLimpar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInserir)
                            .addComponent(btAlterar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btConsulta)
                            .addComponent(btDeletar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotNome)
                            .addComponent(cxVisNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotCpf)
                            .addComponent(cxVisCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotIdade)
                            .addComponent(cxVisIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotSexo)
                            .addComponent(cxVisSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotRg)
                            .addComponent(cxVisRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotPacVis)
                            .addComponent(cxVisPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btInserir)
                            .addComponent(btDeletar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAlterar)
                            .addComponent(btConsulta))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        inserirVisitante();
        popularTbVis();
    }//GEN-LAST:event_btInserirActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        deletarVisitante();
        popularTbVis();
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarVisitante();
        popularTbVis();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        consultarFuncionario();
    }//GEN-LAST:event_btConsultaActionPerformed

    private void tbVisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVisMouseClicked
        selectVis();
    }//GEN-LAST:event_tbVisMouseClicked
    
    public void selectVis(){
        String valLin = "";
        
        int posLin = tbVis.getSelectedRow();
        
        for(int col = 0; col < tbVis.getColumnCount(); col++){
            valLin += tbVis.getModel().getValueAt(posLin, col).toString();
            
            if(col+1< tbVis.getColumnCount()){
                valLin += " - ";
            }
        }
        
        JOptionPane.showMessageDialog(
                null,
                "Valor da linha "+posLin+ " é "+valLin,
                "Saida de Dados",
                JOptionPane.INFORMATION_MESSAGE
        );
        
    }
    
    public void popularTbVis(){
        DefaultTableModel modelo = (DefaultTableModel) tbVis.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Visitante vis: gv.getBdVis()){
            modelo.insertRow(posLin, new Object[]{vis.getNome(), vis.getCpf(),
                vis.getRg(),vis.getIdade(),vis.getPacVis(),vis.getSexo()});
            posLin++;
        }
    }
    
    public void consultarFuncionario(){
        try{
            vis1 = new Visitante();
            vis1.setRg(Integer.parseInt(cxVisRg.getText()));
        
            vis1 = gv.consVisRg(vis1);
        
            if(vis1 != null) {
                cxVisCpf.setText(Integer.toString(vis1.getCpf()));
                cxVisRg.setText(Integer.toString(vis1.getRg()));
                cxVisIdade.setText(Integer.toString(vis1.getIdade()));
                cxVisNome.setText(vis1.getNome());
                cxVisPac.setText(vis1.getPacVis());
                cxVisSexo.setText(vis1.getSexo());
            
                JOptionPane.showMessageDialog(
                    null,
                    "Visitante encontrado, Verifique os dados",
                    "Consulta de Visitantes",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "Não existe Visitante com este RG",
                    "Consulta de Visitante",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }catch(RgException re) {
            limpar();
        }
    }
    
    
    public void alterarVisitante(){
        try{
            vis1 = new Visitante();
            vis1.setRg(Integer.parseInt(cxVisRg.getText()));
        
            vis1 = gv.atualizaVisRg(vis1);
        
            if(vis1 != null){
                cxVisRg.setText(Integer.toString(vis1.getRg()));
                cxVisIdade.setText(Integer.toString(vis1.getIdade()));
                cxVisNome.setText(vis1.getNome());
                cxVisPac.setText(vis1.getPacVis());
                cxVisSexo.setText(vis1.getSexo());
                JOptionPane.showMessageDialog(
                    null,
                    "Visitante alterado! \n Verfique os dados",
                    "Alteração de Visitante",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
            else{
                JOptionPane.showMessageDialog(
                    null,
                    "Não existe visitante com este RG",
                    "Alteração de Visitante",
                    JOptionPane.ERROR_MESSAGE
                );  
            }
            limpar();
        }catch(RgException re) {
            limpar();
        }
    
    
    }
    
    public void deletarVisitante(){
        try{
            vis1 = new Visitante();
            vis1.setRg(Integer.parseInt(cxVisRg.getText()));
            vis1 = gv.delVisRg(vis1);
            if(vis1 == null){
                JOptionPane.showMessageDialog(
                   null,
                   "Visitante deletado",
                   "Exclusão de Visitante",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }   
            else{
                JOptionPane.showMessageDialog(
                    null,
                    "Não existe Visitante com este RG",
                    "Exclusão de Visitante",
                    JOptionPane.ERROR_MESSAGE
                );  
            }
            limpar();
        }catch(RgException re) {
            
        }
    }
    
    public void inserirVisitante(){
        try{
            vis1 = new Visitante();
            vis1.setRg(Integer.parseInt(cxVisRg.getText()));
            vis1.setNome(cxVisNome.getText());
            vis1.setPacVis(cxVisPac.getText());
            vis1.setCpf(Integer.parseInt(cxVisCpf.getText()));
            vis1.setIdade(Integer.parseInt(cxVisIdade.getText()));
            vis1.setSexo(cxVisSexo.getText());
        
            vis1 = gv.insVis(vis1);
        
            if(vis1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Visitante cadastrado",
                        "Cadastro de Visitante",
                        3
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                    null,
                    "ERRO!!\nRg Já existe",
                    "cadastro de Visitante",
                    JOptionPane.ERROR_MESSAGE
                );
                limpar();
            }
        }catch (RgException re) {
            limpar();
        }
    }
    
    public void limpar(){
        cxVisCpf.setText("");
        cxVisNome.setText("");
        cxVisRg.setText("");
        cxVisPac.setText("");
        cxVisSexo.setText("");
        cxVisIdade.setText("");
        cxVisNome.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField cxVisCpf;
    private javax.swing.JTextField cxVisIdade;
    private javax.swing.JTextField cxVisNome;
    private javax.swing.JTextField cxVisPac;
    private javax.swing.JTextField cxVisRg;
    private javax.swing.JTextField cxVisSexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotCpf;
    private javax.swing.JLabel rotIdade;
    private javax.swing.JLabel rotNome;
    private javax.swing.JLabel rotPacVis;
    private javax.swing.JLabel rotRg;
    private javax.swing.JLabel rotSexo;
    private javax.swing.JTable tbVis;
    // End of variables declaration//GEN-END:variables
}
