//Victor Fares Correa Auad Pereira RA2525542

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormCadFunc extends javax.swing.JFrame {
    private Funcionario func1;
    private GerFunc gf = GerFunc.geraGerFunc();
    private static FormCadFunc cadFuncUnic;

    private FormCadFunc() {
        initComponents();
    }
    
    //Singleton
    
    public static FormCadFunc geraCadFunc() {
        if(cadFuncUnic == null) {
            cadFuncUnic = new FormCadFunc();
        }
        return cadFuncUnic;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotNome = new javax.swing.JLabel();
        rotCpf = new javax.swing.JLabel();
        rotIdade = new javax.swing.JLabel();
        rotSexo = new javax.swing.JLabel();
        rotRegistro = new javax.swing.JLabel();
        rotSetor = new javax.swing.JLabel();
        cxFuncNome = new javax.swing.JTextField();
        cxFuncCpf = new javax.swing.JTextField();
        cxFuncIdade = new javax.swing.JTextField();
        cxFuncSexo = new javax.swing.JTextField();
        cxFuncReg = new javax.swing.JTextField();
        cxFuncSetor = new javax.swing.JTextField();
        btInserirFunc = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btDelFunc = new javax.swing.JButton();
        btAltFunc = new javax.swing.JButton();
        btConsFunc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFunc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro De Funcionários");

        rotNome.setText("Nome");

        rotCpf.setText("CPF");

        rotIdade.setText("Idade");

        rotSexo.setText("Sexo");

        rotRegistro.setText("Registro");

        rotSetor.setText("Setor");

        cxFuncSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxFuncSetorActionPerformed(evt);
            }
        });

        btInserirFunc.setText("Inserir");
        btInserirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirFuncActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btDelFunc.setText("Deletar");
        btDelFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelFuncActionPerformed(evt);
            }
        });

        btAltFunc.setText("Alterar");
        btAltFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltFuncActionPerformed(evt);
            }
        });

        btConsFunc.setText("Consulta por Registro");
        btConsFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsFuncActionPerformed(evt);
            }
        });

        tbFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Cpf", "Registro", "Idade", "Setor", "Sexo"
            }
        ));
        tbFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFunc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDelFunc)
                            .addComponent(btInserirFunc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAltFunc)
                            .addComponent(btConsFunc))
                        .addGap(226, 226, 226))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxFuncNome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxFuncCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxFuncSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxFuncReg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxFuncIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxFuncSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btLimpar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotNome)
                            .addComponent(cxFuncNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotCpf)
                            .addComponent(cxFuncCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotIdade)
                            .addComponent(cxFuncIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotSexo)
                            .addComponent(cxFuncSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxFuncReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotSetor)
                            .addComponent(cxFuncSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(btLimpar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserirFunc)
                    .addComponent(btAltFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDelFunc)
                    .addComponent(btConsFunc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxFuncSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxFuncSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxFuncSetorActionPerformed

    private void btInserirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirFuncActionPerformed
        inserirFuncionario();
        popularTbFunc();
    }//GEN-LAST:event_btInserirFuncActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btDelFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelFuncActionPerformed
        deletarFuncionario();
        popularTbFunc();
    }//GEN-LAST:event_btDelFuncActionPerformed

    private void btAltFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltFuncActionPerformed
        alterarFuncionario();
        popularTbFunc();
    }//GEN-LAST:event_btAltFuncActionPerformed

    private void btConsFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsFuncActionPerformed
        consultarFuncionario();
    }//GEN-LAST:event_btConsFuncActionPerformed

    private void tbFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFuncMouseClicked
        selectTbFunc();
    }//GEN-LAST:event_tbFuncMouseClicked
    
    public void selectTbFunc(){
        String valLin = "";
        
        int posLin = tbFunc.getSelectedRow();
        
        for(int col = 0; col < tbFunc.getColumnCount(); col++){
            valLin += tbFunc.getModel().getValueAt(posLin, col).toString();
            
            if(col+1< tbFunc.getColumnCount()){
                valLin += " - ";
            }
        }
        
        JOptionPane.showMessageDialog(
                null,
                "Valor da linha "+posLin+ " é "+valLin,
                "Saida de Dados",
                JOptionPane.INFORMATION_MESSAGE
        );
        
    }
    
    public void popularTbFunc(){
        DefaultTableModel modelo = (DefaultTableModel) tbFunc.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Funcionario func: gf.getBdFunc()){
            modelo.insertRow(posLin, new Object[]{func.getNome(), func.getCpf(),
                func.getRegistro(),func.getIdade(),func.getSetor(),func.getSexo()});
            posLin++;
        }
    }
        
        public void consultarFuncionario(){
        func1 = new Funcionario();
        func1.setRegistro(Integer.parseInt(cxFuncReg.getText()));
        
        func1 = gf.consFuncReg(func1);
        
        if(func1 != null) {
            cxFuncCpf.setText(Integer.toString(func1.getCpf()));
            cxFuncReg.setText(Integer.toString(func1.getRegistro()));
            cxFuncIdade.setText(Integer.toString(func1.getIdade()));
            cxFuncNome.setText(func1.getNome());
            cxFuncSetor.setText(func1.getSetor());
            cxFuncSexo.setText(func1.getSexo());
            
            JOptionPane.showMessageDialog(
                    null,
                    "Funcionario encontrado, Verifique os dados",
                    "Consulta de Funcionarios",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                null,
                "Não existe funcionário com este registro",
                "Consulta de Funcionarios",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    public void alterarFuncionario(){
        func1 = new Funcionario();
        func1.setRegistro(Integer.parseInt(cxFuncReg.getText()));
        
        func1 = gf.atualizaFuncReg(func1);
        
        if(func1 != null){
            cxFuncReg.setText(Integer.toString(func1.getRegistro()));
            cxFuncCpf.setText(Integer.toString(func1.getCpf()));
            cxFuncIdade.setText(Integer.toString(func1.getIdade()));
            cxFuncNome.setText(func1.getNome());
            cxFuncSetor.setText(func1.getSetor());
            cxFuncSexo.setText(func1.getSexo());
            JOptionPane.showMessageDialog(
                    null,
                    "Funcinario alterado! \n Verfique os dados",
                    "Alteração de Funcionario",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                    null,
                    "Não existe funcionário com este registro",
                    "Alteração de Funcionario",
                    JOptionPane.ERROR_MESSAGE
            );  
        }
        limpar();
    
    
    }
    
    public void deletarFuncionario(){
        func1 = new Funcionario();
        func1.setRegistro(Integer.parseInt(cxFuncReg.getText()));
        func1 = gf.delFuncReg(func1);
        if(func1 == null){
            JOptionPane.showMessageDialog(
                null,
                "Funcionario deletado",
                "Exclusão de Funcionário",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe funcionário com este registro",
                "Exclusão de Funcionário",
                JOptionPane.ERROR_MESSAGE
            );  
        }
        limpar();
        
    }
    
    public void inserirFuncionario(){
        func1 = new Funcionario();
        func1.setRegistro(Integer.parseInt(cxFuncReg.getText()));
        func1.setNome(cxFuncNome.getText());
        func1.setSetor(cxFuncSetor.getText());
        func1.setCpf(Integer.parseInt(cxFuncCpf.getText()));
        func1.setIdade(Integer.parseInt(cxFuncIdade.getText()));
        func1.setSexo(cxFuncSexo.getText());
        
        func1 = gf.insFunc(func1);
        
        if(func1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Funcionario cadastrado",
                        "Cadastro de Funcionario",
                        3
                );
                limpar();
        }
        else{
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!!\nRegistro Já existe",
                    "cadastro de Funcionario",
                    JOptionPane.ERROR_MESSAGE
            );
            limpar();
        }
    
    }
    public void limpar(){
        cxFuncCpf.setText("");
        cxFuncNome.setText("");
        cxFuncReg.setText("");
        cxFuncSetor.setText("");
        cxFuncSexo.setText("");
        cxFuncIdade.setText("");
        cxFuncNome.requestFocus();
    }
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltFunc;
    private javax.swing.JButton btConsFunc;
    private javax.swing.JButton btDelFunc;
    private javax.swing.JButton btInserirFunc;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField cxFuncCpf;
    private javax.swing.JTextField cxFuncIdade;
    private javax.swing.JTextField cxFuncNome;
    private javax.swing.JTextField cxFuncReg;
    private javax.swing.JTextField cxFuncSetor;
    private javax.swing.JTextField cxFuncSexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotCpf;
    private javax.swing.JLabel rotIdade;
    private javax.swing.JLabel rotNome;
    private javax.swing.JLabel rotRegistro;
    private javax.swing.JLabel rotSetor;
    private javax.swing.JLabel rotSexo;
    private javax.swing.JTable tbFunc;
    // End of variables declaration//GEN-END:variables
}
