//Victor Fares Correa Auad Pereira RA2525542
public class Principal extends javax.swing.JFrame {

    private static Principal principalUnic;
    private Principal() {
        initComponents();
    }
    
    //singleton
    public Principal geraPrincipal(){
        if(principalUnic == null) {
            principalUnic = new Principal();
        }
        return principalUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadHosp = new javax.swing.JMenu();
        itMnCadPac = new javax.swing.JMenuItem();
        itMnCadMed = new javax.swing.JMenuItem();
        itMnCadFunc = new javax.swing.JMenuItem();
        itMnCadVis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotPrincipal.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        rotPrincipal.setText("Cadastro- Hospital");

        mnCadHosp.setText("Cadastro");

        itMnCadPac.setText("Cadastro de Pacientes");
        itMnCadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadPacActionPerformed(evt);
            }
        });
        mnCadHosp.add(itMnCadPac);

        itMnCadMed.setText("Cadastro de Médicos");
        itMnCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMedActionPerformed(evt);
            }
        });
        mnCadHosp.add(itMnCadMed);

        itMnCadFunc.setText("Cadastrro de Funcionários");
        itMnCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFuncActionPerformed(evt);
            }
        });
        mnCadHosp.add(itMnCadFunc);

        itMnCadVis.setText("Cadastro de Visitantes");
        itMnCadVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadVisActionPerformed(evt);
            }
        });
        mnCadHosp.add(itMnCadVis);

        jMenuBar1.add(mnCadHosp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(rotPrincipal)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rotPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnCadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadPacActionPerformed
        abreCadPac();
    }//GEN-LAST:event_itMnCadPacActionPerformed

    private void itMnCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMedActionPerformed
        abreCadMed();
    }//GEN-LAST:event_itMnCadMedActionPerformed

    private void itMnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFuncActionPerformed
        abreCadFunc();
    }//GEN-LAST:event_itMnCadFuncActionPerformed

    private void itMnCadVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadVisActionPerformed
        abreCadVis();
    }//GEN-LAST:event_itMnCadVisActionPerformed
   
    public void abreCadVis(){
        FormCadVis.geraCadVis().setVisible(true);
    }
    
    public void abreCadFunc(){
        FormCadFunc.geraCadFunc().setVisible(true);
    }
    
    public void abreCadMed(){
        FormCadMed.geraCadMed().setVisible(true);
    }
    
    public void abreCadPac(){
        FormCadPac.geraCadPac().setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itMnCadFunc;
    private javax.swing.JMenuItem itMnCadMed;
    private javax.swing.JMenuItem itMnCadPac;
    private javax.swing.JMenuItem itMnCadVis;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnCadHosp;
    private javax.swing.JLabel rotPrincipal;
    // End of variables declaration//GEN-END:variables
}
